routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\AttendController;
use App\Http\Controllers\PayrollController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return view('beranda');
});

Route::get('/beranda', [MenuController::class, 'home']);
Route::get('/data-employee', [MenuController::class, 'data_employee']);
//Route::get('/data-attend', [MenuController::class, 'data_attend']);
//Route::get('/data-payroll', [MenuController::class, 'data_payroll']);
//Route::get('/data-user', [MenuController::class, 'data_user']); 
Route::get('/data-attend', [AttendController::class, 'index'])->name('attend');
Route::get('/data-user', [UsersController::class, 'index'])->name('users');
Route::get('/data-payroll', [PayrollController::class, 'index'])->name('payroll');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('employee', EmployeeController::class)->middleware('can:isAdmin');
Route::resource('employee', EmployeeController::class)->only('show')->middleware('can:isAdminKaryawan');

Route::resource('users', UsersController::class)->middleware('can:isAdmin');

resources/views/attend.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid text-center mx-auto">
    <p class="text-center"><h5>Employees Attendance</h5></p>
    <table class="table table-sm">
        <tr class="table-info">
            <td><b>No</b></td>
            <td><b>Name</b></td>
            <!-- <td><b>NIK</b></td> -->
            <td><b>Attendance</b></td>
            <td><b>Time Off</b></td>
            <td><b>Description</b></td>
        </tr>
        <?php $no=1;?>
        @foreach($attend as $a)
        <tr>
            <td>{{ $no; }}</td>
            <td>{{ $a->nama }}</td>
            <!-- <td>{{ $a->karyawan_id }}</td> -->
            <td>{{ $a->hadir }}&nbsp;days</td>
            <td>{{ $a->time_off }}&nbsp;days</td>
            <td><i>{{ $a->keterangan }}</i></td>
        </tr>
        <?php $no++ ;?>
        @endforeach
    </table>        
</div>

@endsection

resources/views/beranda.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-danger">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="{{ url('/beranda') }}">Mega Digital Indonesia</a>
              </li>
            </ul>
        <!-- Left Side Of Navbar -->
        <ul class="navbar-nav me-auto">
            @can('isAdmin')
            <li class="nav-item">
                <a class="nav-link text-white" aria-current="page" href="{{ url('/employee') }}">EMPLOYEE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" aria-current="page" href="{{ url('/data-attend') }}">ATTENDANCE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" aria-current="page" href="{{ url('/data-payroll') }}">PAYROLL</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" aria-current="page" href="{{ url('/data-user') }}">USER</a>
            </li>
        @endcan
        </ul>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
          </div>
        </div>
      </nav>

    <div class="container-fluid text-center mx-auto">
        <h2><br/><br/>Employee Data System</h2>
        <p>PT. Mega Digital Indonesia</p>
        {{-- <a href="{{ url('/employee') }}" class="btn btn-outline-secondary">Employees Data</a> --}}
    </div>

    <footer class="fixed-bottom">
        <div class="text-center bg-danger text-white">
            ©2022 FOLITL22
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

resources/views/employee.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid text-center mx-auto">
    <p><h5>Employees Data</h5></p>
    <table class="table table-sm">
        <tr class="table-warning">
            <td><b>No</b></td>
            <td><b>Name</b></td>
            <td><b>Division</b></td>
            <td><b>Section</b></td>
        </tr>
        <tr>
            <td>1</td><td>Hamid</td><td>IT</td><td>Leader</td>
        </tr>
        <tr>
            <td>2</td><td>Haura</td><td>Accounting</td><td>Manager</td>
        </tr>
    </table>        
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid text-center mx-auto table-responsive">
    <p class="text-center"><h5>Employees Data</h5></p>
    <table class="table table-sm">
        <tr>   
            @can('isAdmin')
            <td>
                <a href="{{ route('employee.create') }}" class="btn btn-outline-success" title="add data">
                    <i class="bi bi-arrow-right-circle">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                          </svg>
                    </i>Add
                </a>
            </td>
            @endcan
        </tr>
        <tr class="table-warning">
            <td><b>No</b></td>
            <td><b>Name</b></td>
            <td><b>NIK</b></td>
            <!-- <td><b>NIP</b></td> -->
            <td><b>Address</b></td>
            <td><b>Phone</b></td>
            <!-- <td><b>NPWP</b></td> -->
            <!-- <td><b>Birth of Date</b></td> -->
            @can('isAdmin')
            <td><b>Action</b></td>
            @endcan
        </tr>
        <?php $no=1;?>
        @foreach($employee as $a)
        <tr>
            <td>{{ $no; }}</td>
            <td>{{ $a->nama }}</td>
            <td>{{ $a->nik }}</td>
            <!-- <td>{{ $a->nip }}</td> -->
            <td>{{ $a->alamat }}</td>
            <td>{{ $a->phone }}</td>
            <!-- <td>{{ $a->npwp }}</td> -->
            <!-- <td>{{ $a->tgl_lahir }}</td> -->
            @can('isAdmin')
            <td>
                <ul class="nav">
                    &nbsp; &nbsp;
                    <a href="{{ route('employee.show', $a->id)}}" class="btn btn-secondary mr-2" title="show">
                    <i class="bi bi-search">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                    </svg></i></a>
                    &nbsp;
                    <a href="{{ route('employee.edit', $a->id)}}" class="btn btn-warning mr-2" title="edit">
                    <i class="bi bi-pen">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                    </svg></i></a>
                    &nbsp;
                    <form onsubmit="return confirm('Are you sure want to delete ?');" action="{{ route('employee.destroy', $a->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" title="delete">
                        <i class="bi bi-trash3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg></i>
                        </button>
                    </form>
                </ul>
            </td>
            @endcan
        </tr>
        <?php $no++ ;?>
        @endforeach
    </table>        
</div>

@endsection

resources/views/karyawan_add.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid mx-auto table-responsive">
        <p><h5>Add Employee</h5></p>   
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <form action="{{ route('employee.store') }}" method="POST">
                    @csrf
                    <ul class="list-group">
                        Name <input type="text" name="nama" required placeholder="name">
                        NIK <input type="text" name="nik" required placeholder="nik">
                        NIP <input type="text" name="nip" required placeholder="nip">
                        NPWP <input type="text" name="npwp" required placeholder="npwp">
                        Address <input type="text" name="alamat" required placeholder="address">
                        Phone <input type="text" name="phone" required placeholder="+62">
                        Birth of Date <input type="date" name="tgl_lahir" required>
                    </ul>
                    <br/>
                    <input type="submit" value="Save" class="btn btn-success">
                    <a href="{{ route('employee.index') }}" class="btn btn-primary mr-2">Back</a>
                </form>
            </div>
        </div>       
</div>

@endsection

resources/views/karyawan_edit.blade.php
@extends('layouts.app')

@section('content') 

<div class="container-fluid mx-auto table-responsive">
        <p><h5>Edit Data</h5></p>   
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <form action="{{ route('employee.update', $employee->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <ul class="list-group">
                        Name <input type="text" name="nama" required value="{{ $employee->nama }}">
                        NIK <input type="text" name="nik" required value="{{ $employee->nik }}">
                        NIP <input type="text" name="nip" required value="{{ $employee->nip }}">
                        NPWP <input type="text" name="npwp" required value="{{ $employee->npwp }}">
                        Address <input type="text" name="alamat" required value="{{ $employee->alamat }}">
                        Phone <input type="text" name="phone" required value="{{ $employee->phone }}">
                        Birth of Date <input type="date" name="tgl_lahir" required value="{{ $employee->tgl_lahir }}">
                    </ul>
                    <br/>
                    <input type="submit" value="Edit" class="btn btn-success">
                    <a href="{{ route('employee.index') }}" class="btn btn-primary mr-2">Back</a>
                </form>
            </div>
        </div>       
</div>

@endsection

resources/views/payroll.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid text-center mx-auto">
    <p><h5>Salary Payments Information</h5></p>
    <table class="table table-sm">
        <tr class="table-success">
            <td><b>No</b></td>
            <td><b>Date</b></td>
            <td><b>Name</b></td>
            <td><b>Salary</b></td>
            <td><b>Allowance</b></td>
            <td><b>NPWP</b></td>
            <td><b>BPJS Ketenaga Kerjaan</b></td>
            <td><b>BPJS Kesehatan</b></td>
            <td><b>Status</b></td>
        </tr>
        <?php $no=1;?>
        @foreach($payroll as $a)
        <tr>
            <td>{{ $no; }}</td>
            <td>{{ date('d F Y', strtotime($a->paydate)) }}</td>
            <td>{{ $a->nama }}</td>
            <td>Rp {{ number_format($a->salary,2,',','.') }}</td>
            <td>Rp {{ number_format($a->allowance,2,',','.') }}</td>
            <td>Rp {{ number_format($a->npwp,2,',','.') }}</td>
            <td>Rp {{ number_format($a->bpjs_kerja,2,',','.') }}</td>
            <td>Rp {{ number_format($a->bpjs_kes,2,',','.') }}</td>
            <td><i>{{ $a->status }}</i></td>
        </tr>
        <?php $no++ ;?>
        @endforeach
    </table>        
</div>

@endsection

resources/views/profil_karyawan.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid mx-auto table-responsive">
    <p>Employee's Profile</p>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ $employee->nama }}</h5>
            <p class="card-text">{{ $employee->nik }}</p>
            <p class="card-text">NIP. {{ $employee->nip }}</p>
            <p class="card-text">NPWP. {{ $employee->npwp }}</p>
            <p class="card-text">📞 {{ $employee->phone }}</p>
            <p class="card-text">🏠 {{ $employee->alamat }}</p>
            <p class="card-text">🎂 {{ $employee->tgl_lahir }}</p>
        </div>
        @can('isAdmin')
        <a href="{{ route('employee.index') }}" class="btn btn-info">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-back" viewBox="0 0 16 16">
            <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm2-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2z"/>
        </svg>&nbsp; Back</a>
        @endcan
    </div>       
</div>

@endsection

resources/views/user_edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid mx-auto table-responsive">
        <p><h5>Edit Data</h5></p>   
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <form action="{{ route('users.update', $users->id) }}" method="POST">
                    @csrf 
                    @method('PUT')
                    <ul class="list-group">
                    Name <input type="text" name="name" required value="{{  $users->name }}">
                    Role <select id="role" name="role" required>
                            <option>{{ $users->role }}</option>
                            <option value="Admin">Admin</option>
                            <option value="Karyawan">Staff</option>
                        </select>
                    ID Access <input type="text" name="karyawan_id" placeholder="ID Access" value="{{ $users->karyawan_id }}">
                    E-mail <input type="email" name="email" placeholder="abcde@email.com" required value="{{ $users->email }}">
                    Password <input type="password" name="password" minlength="8" required placeholder="input your password">
                </br>
                </ul>
                    <input type="submit" value="Edit" class="btn btn-success">
                    <a href="{{ route('users.index') }}" class="btn btn-primary mr-2">Back</a>
                </form>
            </div>
        </div>       
</div>

@endsection

resources/views/users.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid text-center mx-auto table-responsive">
    <p class="text-center"><h5>Users Management</h5></p>
    <table class="table table-sm">   
        <tr class="table-light">
            <td><b>No</b></td>
            <td><b>Name</b></td>
            <!-- <td><b>NIK</b></td> -->
            <td><b>Role</b></td>
            <td><b>Email</b></td>
            <td><b>Action</b></td>
        </tr>
        <?php $no=1;?>
        @foreach($users as $a)
        <tr> 
            <td>{{ $no; }}</td>
            <td>{{ $a->name }}</td>
           <!-- <td>{{ $a->karyawan_id }}</td> -->
            <td>{{ $a->role }}</td>
            <td>{{ $a->email }}</td>
            <td>
                <ul class="nav">
                    &nbsp; &nbsp;
                    <a href="{{ route('users.edit', $a->id)}}" class="btn btn-warning mr-2" title="edit">
                    <i class="bi bi-pen">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                    </svg></i></a>
                    &nbsp;
                    <form onsubmit="return confirm('Are you sure want to delete ?');" action="{{ route('users.destroy', $a->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" title="delete">
                        <i class="bi bi-trash3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                        </svg></i>
                        </button>
                    </form>
                </ul>
</td>
        </tr>
        <?php $no++ ;?>
        @endforeach
    </table>        
</div>

@endsection